In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
df = pd.read_csv('emi_dataset.csv', low_memory=False)
print("Dataset loaded!")
print("Shape:", df.shape)

Dataset loaded!
Shape: (404800, 27)

In [3]:
df.head()

,age,gender,marital_status,education,monthly_salary,employment_type,years_of_employment,company_type,house_type,monthly_rent,family_size,dependents,school_fees,college_fees,travel_expenses,groceries_utilities,other_monthly_expenses,existing_loans,current_emi_amount,credit_score,bank_balance,emergency_fund,emi_scenario,requested_amount,requested_tenure,emi_eligibility,max_monthly_emi
0,38,Female,Married,Professional,82600.0,Private,0.90,Mid-size,Rented,20000.00,3,2,0.00,0.00,7200.00,19500.00,13200.00,Yes,23700.00,660.00,303200.0,70200.00,Personal Loan EMI,850000.00,15,Not_Eligible,500.00
1,38,Female,Married,Graduate,21500.0,Private,7.00,MNC,Family,0.00,2,1,5100.00,0.00,1400.00,5400.00,3500.00,Yes,4100.00,714.00,92500.0,26900.00,E-commerce Shopping EMI,128000.00,19,Not_Eligible,700.00
2,38,Male,Married,Professional,86100.0,Private,5.80,Startup,Own,0.00,4,3,0.00,0.00,10200.00,19400.00,6000.00,No,0.00,650.00,672100.0,324200.00,Education EMI,306000.00,16,Eligible,27775.00
3,58,Female,Married,High School,66800.0,Private,2.20,Mid-size,Own,0.00,5,4,11400.00,0.00,6200.00,11900.00,7900.00,No,0.00,685.00,440900.0,178100.00,Vehicle EMI,304000.00,83,Eligible,16170.00
4,48,Female,Married,Professional,57300.0,Private,3.40,Mid-size,Family,0.00,4,3,9400.00,21300.00,3600.00,16200.00,8100.00,No,0.00,770.00,97300.0,28200.00,Home Appliances EMI,252000.00,7,Not_Eligible,500.00

In [4]:
df['monthly_salary'].count()

np.int64(404800)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 404800 entries, 0 to 404799
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   age                     404800 non-null  str
 1   gender                  404800 non-null  str
 2   marital_status          404800 non-null  str
 3   education               402396 non-null  str
 4   monthly_salary          404800 non-null  str
 5   employment_type         404800 non-null  str
 6   years_of_employment     404800 non-null  float64
 7   company_type            404800 non-null  str
 8   house_type              404800 non-null  str
 9   monthly_rent            402374 non-null  float64
 10  family_size             404800 non-null  int64
 11  dependents              404800 non-null  int64
 12  school_fees             404800 non-null  float64
 13  college_fees            404800 non-null  float64
 14  travel_expenses         404800 non-null  float64
 15  groceries_utilities     404800 non-null  float64
 16  other_monthly_expenses  404800 non-null  float64
 17  existing_loans          404800 non-null  str
 18  current_emi_amount      404800 non-null  float64
 19  credit_score            402380 non-null  float64
 20  bank_balance            402374 non-null  str
 21  emergency_fund          402449 non-null  float64
 22  emi_scenario            404800 non-null  str
 23  requested_amount        404800 non-null  float64
 24  requested_tenure        404800 non-null  int64
 25  emi_eligibility         404800 non-null  str
 26  max_monthly_emi         404800 non-null  float64
dtypes: float64(12), int64(3), str(12)
memory usage: 83.4 MB

In [6]:
df.describe()

,years_of_employment,monthly_rent,family_size,dependents,school_fees,college_fees,travel_expenses,groceries_utilities,other_monthly_expenses,current_emi_amount,credit_score,emergency_fund,requested_amount,requested_tenure,max_monthly_emi
count,404800.00,402374.00,404800.00,404800.00,404800.00,404800.00,404800.00,404800.00,404800.00,404800.00,402380.00,402449.00,404800.00,404800.00,404800.00
mean,5.36,5828.45,2.94,1.94,4624.58,4066.25,5687.50,12805.00,7119.31,4543.41,700.86,96769.05,370855.40,29.13,6763.60
std,6.08,8648.60,1.08,1.08,5061.07,7319.34,3392.67,6993.85,4510.45,7034.90,88.44,81373.05,345194.52,18.10,7741.26
min,0.50,0.00,1.00,0.00,0.00,0.00,600.00,1800.00,600.00,0.00,0.00,1400.00,10000.00,3.00,500.00
25%,1.20,0.00,2.00,1.00,0.00,0.00,3200.00,7700.00,3800.00,0.00,654.00,38400.00,124000.00,15.00,500.00
50%,3.20,0.00,3.00,2.00,3000.00,0.00,4900.00,11400.00,6000.00,0.00,701.00,74000.00,236000.00,25.00,4211.20
75%,7.20,10600.00,4.00,3.00,9000.00,6500.00,7400.00,16400.00,9300.00,8000.00,748.00,130600.00,494000.00,40.00,9792.00
max,36.00,80000.00,5.00,4.00,15000.00,25000.00,30300.00,71200.00,42900.00,56300.00,1200.00,891500.00,1500000.00,84.00,91040.40

In [7]:
df['school_fees'].head()

0       0.00
1    5100.00
2       0.00
3   11400.00
4    9400.00
Name: school_fees, dtype: float64

In [8]:
# pd.to_numeric with errors='coerce' converts bad values to NaN
# We count how many become NaN per column
for col in ['age', 'monthly_salary', 'bank_balance']:
    bad = pd.to_numeric(df[col], errors='coerce').isna().sum()
    print(f"{col}: {bad} non-numeric values")

age: 3 non-numeric values
monthly_salary: 1993 non-numeric values
bank_balance: 4392 non-numeric values

In [9]:
# Convert to numeric, coercing errors to NaN
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df['monthly_salary'] = pd.to_numeric(df['monthly_salary'], errors='coerce')
df['bank_balance'] = pd.to_numeric(df['bank_balance'], errors='coerce')

print("Done! New dtypes:")
print(df[['age', 'monthly_salary', 'bank_balance']].dtypes)

Done! New dtypes:
age               float64
monthly_salary    float64
bank_balance      float64
dtype: object

In [10]:
df['gender'] = df['gender'].str.strip().str.capitalize()
df['gender'] = df['gender'].replace({'M': 'Male', 'F': 'Female'})

print(df['gender'].unique())

<StringArray>
['Female', 'Male']
Length: 2, dtype: str

In [11]:
duplicates = df.duplicated().sum()
print(f"Duplicate rows: {duplicates}")

Duplicate rows: 0

In [12]:
# Check unique values in categorical columns
missing = df.isnull().sum()
missing = missing[missing > 0]
missing_pct = (missing / len(df) * 100).round(2)

missing_df = pd.DataFrame({'Missing Count': missing, 'Percentage': missing_pct})
print(missing_df)

                Missing Count  Percentage
age                         3        0.00
education                2404        0.59
monthly_salary           1993        0.49
monthly_rent             2426        0.60
credit_score             2420        0.60
bank_balance             4392        1.08
emergency_fund           2351        0.58

In [13]:
# Numerical — fill with median
for col in ['age', 'monthly_salary', 'credit_score', 'bank_balance', 'emergency_fund']:
    df[col] = df[col].fillna(df[col].median())

# monthly_rent — 0 makes sense (owned house = no rent)
df['monthly_rent'] = df['monthly_rent'].fillna(0)

# education — fill with most common value
df['education'] = df['education'].fillna(df['education'].mode()[0])

print("Missing values remaining:")
print(df.isnull().sum().sum())

Missing values remaining:
0

In [14]:
print(df.isnull().sum()[df.isnull().sum() > 0])

Series([], dtype: int64)

In [15]:
# Check data types and duplicates again after cleaning
print("Shape:", df.shape)
print("\nData types:")
print(df.dtypes)
print("\nMissing values:", df.isnull().sum().sum())
print("\nDuplicates:", df.duplicated().sum())

Shape: (404800, 27)

Data types:
age                       float64
gender                        str
marital_status                str
education                     str
monthly_salary            float64
employment_type               str
years_of_employment       float64
company_type                  str
house_type                    str
monthly_rent              float64
family_size                 int64
dependents                  int64
school_fees               float64
college_fees              float64
travel_expenses           float64
groceries_utilities       float64
other_monthly_expenses    float64
existing_loans                str
current_emi_amount        float64
credit_score              float64
bank_balance              float64
emergency_fund            float64
emi_scenario                  str
requested_amount          float64
requested_tenure            int64
emi_eligibility               str
max_monthly_emi           float64
dtype: object

Missing values: 0

Duplicates: 0

In [16]:
df['age'] = df['age'].astype(int)
print(df['age'].dtype)
print(df['age'].head())

int64
0    38
1    38
2    38
3    58
4    48
Name: age, dtype: int64

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 404800 entries, 0 to 404799
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   age                     404800 non-null  int64
 1   gender                  404800 non-null  str
 2   marital_status          404800 non-null  str
 3   education               404800 non-null  str
 4   monthly_salary          404800 non-null  float64
 5   employment_type         404800 non-null  str
 6   years_of_employment     404800 non-null  float64
 7   company_type            404800 non-null  str
 8   house_type              404800 non-null  str
 9   monthly_rent            404800 non-null  float64
 10  family_size             404800 non-null  int64
 11  dependents              404800 non-null  int64
 12  school_fees             404800 non-null  int64
 13  college_fees            404800 non-null  int64
 14  travel_expenses         404800 non-null  int64
 15  groceries_utilities     404800 non-null  int64
 16  other_monthly_expenses  404800 non-null  int64
 17  existing_loans          404800 non-null  str
 18  current_emi_amount      404800 non-null  float64
 19  credit_score            404800 non-null  float64
 20  bank_balance            404800 non-null  float64
 21  emergency_fund          404800 non-null  float64
 22  emi_scenario            404800 non-null  str
 23  requested_amount        404800 non-null  float64
 24  requested_tenure        404800 non-null  int64
 25  emi_eligibility         404800 non-null  str
 26  max_monthly_emi         404800 non-null  float64
dtypes: float64(9), int64(9), str(9)
memory usage: 83.4 MB

In [18]:
df.head()

,age,gender,marital_status,education,monthly_salary,employment_type,years_of_employment,company_type,house_type,monthly_rent,family_size,dependents,school_fees,college_fees,travel_expenses,groceries_utilities,other_monthly_expenses,existing_loans,current_emi_amount,credit_score,bank_balance,emergency_fund,emi_scenario,requested_amount,requested_tenure,emi_eligibility,max_monthly_emi
0,38,Female,Married,Professional,82600.00,Private,0.90,Mid-size,Rented,20000.00,3,2,0.00,0.00,7200.00,19500.00,13200.00,Yes,23700.00,660.00,303200.00,70200.00,Personal Loan EMI,850000.00,15,Not_Eligible,500.00
1,38,Female,Married,Graduate,21500.00,Private,7.00,MNC,Family,0.00,2,1,5100.00,0.00,1400.00,5400.00,3500.00,Yes,4100.00,714.00,92500.00,26900.00,E-commerce Shopping EMI,128000.00,19,Not_Eligible,700.00
2,38,Male,Married,Professional,86100.00,Private,5.80,Startup,Own,0.00,4,3,0.00,0.00,10200.00,19400.00,6000.00,No,0.00,650.00,672100.00,324200.00,Education EMI,306000.00,16,Eligible,27775.00
3,58,Female,Married,High School,66800.00,Private,2.20,Mid-size,Own,0.00,5,4,11400.00,0.00,6200.00,11900.00,7900.00,No,0.00,685.00,440900.00,178100.00,Vehicle EMI,304000.00,83,Eligible,16170.00
4,48,Female,Married,Professional,57300.00,Private,3.40,Mid-size,Family,0.00,4,3,9400.00,21300.00,3600.00,16200.00,8100.00,No,0.00,770.00,97300.00,28200.00,Home Appliances EMI,252000.00,7,Not_Eligible,500.00

In [19]:
# Convert all financial columns to int (after filling missing values)
df['college_fees'] = df['college_fees'].astype(int)
df['travel_expenses'] = df['travel_expenses'].astype(int)
df['groceries_utilities'] = df['groceries_utilities'].astype(int)
df['other_monthly_expenses'] = df['other_monthly_expenses'].astype(int)
df['school_fees'] = df['school_fees'].astype(int)

In [22]:
X = df.drop(columns=['emi_eligibility', 'max_monthly_emi'])
y_class = df['emi_eligibility']
y_reg = df['max_monthly_emi']

print("Features shape:", X.shape)
print("Classification target:", y_class.unique())
print("Regression target stats:")
print(y_reg.describe())

Features shape: (404800, 25)
Classification target: <StringArray>
['Not_Eligible', 'Eligible', 'High_Risk']
Length: 3, dtype: str
Regression target stats:
count   404800.00
mean      6763.60
std       7741.26
min        500.00
25%        500.00
50%       4211.20
75%       9792.00
max      91040.40
Name: max_monthly_emi, dtype: float64

In [28]:
df['emi_eligibility'].unique()

<StringArray>
['Not_Eligible', 'Eligible', 'High_Risk']
Length: 3, dtype: str

In [24]:
from sklearn.model_selection import train_test_split

# First split: 70% train, 30% temp
X_train, X_temp, y_class_train, y_class_temp, y_reg_train, y_reg_temp = train_test_split(
    X, y_class, y_reg, test_size=0.30, random_state=42, stratify=y_class
)

# Second split: 50% of temp = 15% val, 15% test
X_val, X_test, y_class_val, y_class_test, y_reg_val, y_reg_test = train_test_split(
    X_temp, y_class_temp, y_reg_temp, test_size=0.50, random_state=42, stratify=y_class_temp
)

print("Train:", X_train.shape)
print("Validation:", X_val.shape)
print("Test:", X_test.shape)

Train: (283360, 25)
Validation: (60720, 25)
Test: (60720, 25)

In [25]:
import os

os.makedirs('data', exist_ok=True)

# Save cleaned full dataset
df.to_csv('data/cleaned_data.csv', index=False)

# Save splits
X_train.to_csv('data/X_train.csv', index=False)
X_val.to_csv('data/X_val.csv', index=False)
X_test.to_csv('data/X_test.csv', index=False)

y_class_train.to_csv('data/y_class_train.csv', index=False)
y_class_val.to_csv('data/y_class_val.csv', index=False)
y_class_test.to_csv('data/y_class_test.csv', index=False)

y_reg_train.to_csv('data/y_reg_train.csv', index=False)
y_reg_val.to_csv('data/y_reg_val.csv', index=False)
y_reg_test.to_csv('data/y_reg_test.csv', index=False)

print("All files saved in /data folder!")

All files saved in /data folder!